name: CLA Assistant
on:
  workflow_dispatch: {}
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
    - name: CLA Assistant
      if: (github.event.comment.body == 'recheck' || github.event.comment.body ==
        'I have read the CLA Document and I hereby sign the CLA') || github.event_name
        == 'pull_request_target'
      uses: contributor-assistant/github-action@v2.6.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_ACCESS_TOKEN: ${{ secrets.CDRCOMMUNITY_GITHUB_TOKEN }}
      with:
        remote-organization-name: coder
        remote-repository-name: cla
        path-to-signatures: v2022-09-04/signatures.json
        path-to-document: https://github.com/coder/cla/blob/main/README.md
        branch: main
        allowlist: dependabot*
