name: lint/go
on:
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9.2.0
      with:
        version: v2.1.2
